name: cicd
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13' # The Go version to download (if necessary) and use.
    - run: go build
    - if: failure()
          
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13' # The Go version to download (if necessary) and use.
    - run: go build
    - if: failure()

    - name: copy file to remote using ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPSHOST }}
        username: ${{ secrets.VPSUSER }}
        key: ${{ secrets.SSHPRIVATE }}
        port: ${{ secrets.VPSPORT }}
        source: "."
        target: "${{ secrets.VPSPATH }}"

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPSHOST }}
        username: ${{ secrets.VPSUSER }}
        key: ${{ secrets.SSHPRIVATE }}
        port: ${{ secrets.VPSPORT }}
        script: cd ${{ secrets.VPSPATH }} && go build 
