name: buildndeploy
on: [push]
jobs:

  buildndeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - run: go build
    if: ${{ success() }}
    - uses: actions/checkout@master
    - name: copy file to remote using ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPSHOST }}
        username: ${{ secrets.VPSUSER }}
        key: ${{ secrets.SSHPRIVATE }}
        port: ${{ secrets.VPSPORT }}
        source: "."
        target: "${{ secrets.VPSPATH }}"

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPSHOST }}
        username: ${{ secrets.VPSUSER }}
        key: ${{ secrets.SSHPRIVATE }}
        port: ${{ secrets.VPSPORT }}
        script: cd ${{ secrets.VPSPATH }} && go build 