name: Test
on: [push, pull_request]
jobs:
  tests:
    name: Unit and integrations tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.13]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          sudo /etc/init.d/mysql start
          while ! mysqladmin ping --silent; do
            sleep 1
          done
          sudo mysql -proot -e 'CREATE DATABASE goyave CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
          sudo mysql -proot -e 'CREATE USER "goyave"@"%" IDENTIFIED BY "secret"'
          sudo mysql -proot -e 'GRANT ALL PRIVILEGES ON goyave.* TO "goyave"@"%"'
          go test -v -race ./...